services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    working_dir: /app
    ports:
      - "4321:4321"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
    command: dev
    tty: true
    stdin_open: true
    init: true
    security_opt:
      - no-new-privileges:true
    user: node
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4321"]
      interval: 10s
      timeout: 5s
      retries: 3

  test:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    command: test
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: test
    depends_on:
      web:
        condition: service_healthy

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    command: cypress
    ports:
      - "9323:9323"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      CYPRESS_BASE_URL: http://web:4321
    depends_on:
      web:
        condition: service_healthy

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    command: storybook
    ports:
      - "6006:6006"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
      STORYBOOK_DISABLE_TELEMETRY: 1
    depends_on:
      web:
        condition: service_healthy

  lint:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    command: lint
    volumes:
      - ./:/app:cached
      - /app/node_modules
    depends_on:
      web:
        condition: service_healthy

  format:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    command: format
    volumes:
      - ./:/app:cached
      - /app/node_modules
    depends_on:
      web:
        condition: service_healthy