services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.cursor  # referencia explícita al Dockerfile personalizado
    working_dir: /app
    ports:
      - "4321:4321"
    volumes:
      - ./:/app:cached
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
    command: npm run dev
    tty: true
    stdin_open: true
    init: true
    security_opt:
      - no-new-privileges:true
    user: node