/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  safelist: [
    // Gradientes para las tarjetas del equipo
    'from-blue-500',
    'to-blue-300',
    'from-purple-500',
    'to-purple-300',
    'from-orange-500',
    'to-orange-300',
    'from-indigo-500',
    'to-indigo-300',
    'from-green-500',
    'to-green-300',
    // Clases adicionales para orange y amber
    'bg-orange-500',
    'bg-orange-300',
    'from-amber-500',
    'to-amber-300',
    'bg-gradient-to-r',
    'from-orange-500',
    'to-orange-300',
    // Colores de tags
    'bg-orange-50',
    'text-orange-600',
    // Gradientes anteriores por compatibilidad
    'to-teal-400',
    'to-pink-400',
    'from-amber-500',
    'to-orange-400',
    'to-blue-400',
    'to-emerald-400',
    'from-teal-500',
    'to-green-400',
    'from-emerald-500',
    'to-teal-400',
    // Clases específicas para las tarjetas del equipo en index.astro
    'bg-blue-50',
    'text-blue-600',
    'bg-purple-50',
    'text-purple-600',
    'bg-green-50',
    'text-green-600',
    'bg-orange-50',
    'text-orange-600',
    'bg-amber-50',
    'text-amber-600',
    'bg-indigo-50',
    'text-indigo-600',
    'from-blue-50',
    'to-teal-50',
    'from-purple-50',
    'to-pink-50',
    'from-green-50',
    'to-teal-50',
    'from-orange-50',
    'to-amber-50',
    'from-amber-50',
    'to-orange-50',
    'from-indigo-50',
    'to-blue-50',
    'from-blue-200/40',
    'from-teal-200/40',
    'from-purple-200/40',
    'from-pink-200/40',
    'from-green-200/40',
    'from-orange-200/40',
    'from-amber-200/40',
    'from-indigo-200/40',
    'border-blue-200',
    'border-purple-200',
    'border-green-200',
    'border-orange-200',
    'border-amber-200',
    'border-indigo-200',
    'text-blue-600',
    'text-purple-600',
    'text-green-600',
    'text-orange-600',
    'text-amber-600',
    'text-indigo-600',
    'hover:text-teal-500',
    'hover:text-pink-600',
    'hover:text-teal-600',
    'hover:text-amber-600',
    'hover:text-orange-600',
    'hover:text-blue-600',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#3B82F6',
          light: '#60A5FA',
          dark: '#2563EB',
        },
        secondary: {
          DEFAULT: '#0EA5E9',
          light: '#38BDF8',
          dark: '#0284C7',
        },
        sky: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        // Nuevos colores por especialidad
        medicina: {
          DEFAULT: '#3b82f6',
          light: '#eff6ff',
          dark: '#2563eb',
        },
        psico: {
          DEFAULT: '#8b5cf6',
          light: '#f5f3ff',
          dark: '#7c3aed',
        },
        terapias: {
          DEFAULT: '#10b981',
          light: '#ecfdf5',
          dark: '#059669',
        },
        psicologia: {
          DEFAULT: '#f59e0b',
          light: '#fffbeb',
          dark: '#d97706',
        },
        // Colores complementarios
        teal: '#2dd4bf',
        pink: '#f472b6',
      },
      backgroundColor: theme => ({
        ...theme('colors'),
        page: '#ffffff',
      }),
      gradientColorStops: theme => ({
        ...theme('colors'),
        'sky-gradient-start': '#e0f2fe',
        'sky-gradient-end': '#ffffff',
      }),
      backgroundImage: {
        'medicina-gradient': 'linear-gradient(to right, #3b82f6, #2dd4bf)',
        'psico-gradient': 'linear-gradient(to right, #8b5cf6, #f472b6)',
        'terapias-gradient': 'linear-gradient(to right, #10b981, #2dd4bf)',
        'psicologia-gradient': 'linear-gradient(to right, #f59e0b, #fb923c)',
      },
      fontFamily: {
        sans: ['Montserrat', 'sans-serif'],
        serif: ['Merriweather', 'serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
  ],
};
